const MoviesArray = [
    {
        id:"1",
        title:"Loki",
        image:"https://lumiere-a.akamaihd.net/v1/images/tra8660_105_trl_comp_v004_7f1c1cb3.jpeg?region=491,0,2858,1608",
        wallpaper:"https://rare-gallery.com/mocahbig/85901-loki-tv-shows-hd-4k-5k-marvel-behance.jpg",
        description:"After stealing the Tesseract during the events of Avengers: Endgame. an alternate version of Loki is brought to the mysterious.",
        duration:"52 min",
        ratings:"8.2",
        quality:"HD",
        genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
        realised:"2021-06-09",
        casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
        production:"Marvel Studios",
        country:"United States of America",
    },
    {
        id:"2",
        title:"The Marsh King's Daughter",
        image:"https://img.sflix.to/xxrz/250x400/224/f4/55/f4554ab27d86f77087c693db75b661fd/f4554ab27d86f77087c693db75b661fd.jpg",
        wallpaper:"https://m.media-amazon.com/images/S/sonata-images-prod/US_TVOD_TheMarshKingsDaughter_PVOD_SH/d6f6de4a-541f-4c0e-8570-9faf668420ca._UR1920,1080_SX1440_FMjpg_.jpeg",
        description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
        duration:"108 minn",
        ratings:"6.2",
        quality:"HD",
        genre:"Thriller, Drama",
        realised:"2023-09-28",
        casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
        production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
        country:"United States of America",
    },
    {
        id:"3",
        title:"Wish",
        image:"https://images.justwatch.com/poster/309134585/s592/wish-2023",
        wallpaper:"https://images.hdqwalls.com/wallpapers/disney-wish-2023-kv.jpg",
        description:"Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
        duration:"52 min",
        ratings:"8.2",
        quality:"HD",
        genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
        realised:"2021-06-09",
        casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
        production:"Marvel Studios",
        country:"United States of America",
    },
    {
        id:"4",
        title:"Mission: Impossible - Dead Reckoning Part One",
        image:"https://img.sflix.to/xxrz/250x400/224/e5/a0/e5a02d6b78afd13554c6737c1da83cae/e5a02d6b78afd13554c6737c1da83cae.jpg",
        wallpaper:"https://images.hdqwalls.com/wallpapers/2023-mission-impossible-dead-reckoning-part-one-poster-8e.jpg",
        description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
        duration:"108 minn",
        ratings:"6.2",
        quality:"HD",
        genre:"Thriller, Drama",
        realised:"2023-09-28",
        casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
        production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
        country:"United States of America",
    },
    {
        id:"5",
        title:"Black Panthar",
        image:"https://cdn.wallpapersafari.com/42/14/086aOW.jpg",
        wallpaper:"https://www.bhmpics.com/downloads/movie-poster-2018-Wallpapers/30.a94b8bf77d4ca19fde5930678f9f8999.jpg",
        description:"Deep in the Rocky Mountains of Colorado, a government blacksite going by the name Valkyrie, conducts their twisted human experiments trying to push the boundaries of human evolution. Their operation becomes compromised when experiment #030, a.k.a. Sirona, escapes. In a desperate attempt to maintain their secret, Valkyrie hires a group of mercenaries led by Allen Cross to hunt down Sirona and capture her, whatever the cost. Upon finding Sirona, Cross is forced into a no win scenario, do the right thing or follow orders, both of which lead to dire consequences.",
        duration:"52 min",
        ratings:"8.2",
        quality:"HD",
        genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
        realised:"2021-06-09",
        casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
        production:"Marvel Studios",
        country:"United States of America",
    },
    {
        id:"6",
        title:"Entergalactic",
        image:"https://img.sflix.to/xxrz/250x400/224/99/7f/997fdcdc8228bddd182c663a7e16f590/997fdcdc8228bddd182c663a7e16f590.jpg",
        wallpaper:"https://images6.alphacoders.com/132/1321794.jpeg",
        description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
        duration:"108 minn",
        ratings:"6.2",
        quality:"HD",
        genre:"Thriller, Drama",
        realised:"2023-09-28",
        casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
        production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
        country:"United States of America",
    },
    {
        id:"7",
        title:"Sago Mini Friends",
        image:"https://img.sflix.to/xxrz/250x400/224/04/71/04716ddc953df3bdb7178bb63e38c5ae/04716ddc953df3bdb7178bb63e38c5ae.jpg",
        wallpaper:"https://www.apple.com/tv-pr/articles/2022/08/apple-tv-reveals-trailer-for-sago-mini-friends-an-adorable-new-preschool-animated-series-based-on-the-award-winning-app-sago-mini-world/images/big-image/big-image-01/083022_Reveals_Trailer_Sago_Mini_Friends_Big_Image_01_big_image_post.jpg.og.jpg",
        description:"After stealing the Tesseract during the events of Avengers: Endgame. an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant”or help fix the timeline and stop a greater threat",
        duration:"52 min",
        ratings:"8.2",
        quality:"HD",
        genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
        realised:"2021-06-09",
        casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
        production:"Marvel Studios",
        country:"United States of America",
    },
    {
        id:"8",
        title:"The Creator",
        image:"https://img.sflix.to/xxrz/250x400/224/0b/e7/0be7bc9996857aae6580e0aaf103084a/0be7bc9996857aae6580e0aaf103084a.jpg",
        wallpaper:"https://wallpapercg.com/download/john-david-washington-7680x4788-16946.jpg",
        description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
        duration:"108 minn",
        ratings:"6.2",
        quality:"HD",
        genre:"Thriller, Drama",
        realised:"2023-09-28",
        casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
        production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
        country:"United States of America",
    },
    {
        id:"9",
        title:"Loki",
        image:"https://lumiere-a.akamaihd.net/v1/images/tra8660_105_trl_comp_v004_7f1c1cb3.jpeg?region=491,0,2858,1608",
        wallpaper:"https://rare-gallery.com/mocahbig/85901-loki-tv-shows-hd-4k-5k-marvel-behance.jpg",
        description:"After stealing the Tesseract during the events of Avengers: Endgame. an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant”or help fix the timeline and stop a greater threat",
        duration:"52 min",
        ratings:"8.2",
        quality:"HD",
        genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
        realised:"2021-06-09",
        casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
        production:"Marvel Studios",
        country:"United States of America",
    },
    {
        id:"10",
        title:"The Marsh King's Daughter",
        image:"https://img.sflix.to/xxrz/250x400/224/f4/55/f4554ab27d86f77087c693db75b661fd/f4554ab27d86f77087c693db75b661fd.jpg",
        wallpaper:"https://m.media-amazon.com/images/S/sonata-images-prod/US_TVOD_TheMarshKingsDaughter_PVOD_SH/d6f6de4a-541f-4c0e-8570-9faf668420ca._UR1920,1080_SX1440_FMjpg_.jpeg",
        description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
        duration:"108 minn",
        ratings:"6.2",
        quality:"HD",
        genre:"Thriller, Drama",
        realised:"2023-09-28",
        casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
        production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
        country:"United States of America",
    },
    // {
    //     id:"11",
    //     title:"Wish",
    //     image:"https://images.justwatch.com/poster/309134585/s592/wish-2023",
    //     wallpaper:"https://images.hdqwalls.com/wallpapers/disney-wish-2023-kv.jpg",
    //     description:"Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
    //     duration:"52 min",
    //     ratings:"8.2",
    //     quality:"HD",
    //     genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
    //     realised:"2021-06-09",
    //     casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
    //     production:"Marvel Studios",
    //     country:"United States of America",
    // },
    // {
    //     id:"12",
    //     title:"Mission: Impossible - Dead Reckoning Part One",
    //     image:"https://img.sflix.to/xxrz/250x400/224/e5/a0/e5a02d6b78afd13554c6737c1da83cae/e5a02d6b78afd13554c6737c1da83cae.jpg",
    //     wallpaper:"https://images.hdqwalls.com/wallpapers/2023-mission-impossible-dead-reckoning-part-one-poster-8e.jpg",
    //     description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    //     duration:"108 minn",
    //     ratings:"6.2",
    //     quality:"HD",
    //     genre:"Thriller, Drama",
    //     realised:"2023-09-28",
    //     casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
    //     production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
    //     country:"United States of America",
    // },
    // {
    //     id:"13",
    //     title:"Sirona",
    //     image:"https://img.sflix.to/xxrz/250x400/224/03/64/03641b0e4d09722be48de99a4c7236d9/03641b0e4d09722be48de99a4c7236d9.jpg",
    //     wallpaper:"https://rare-gallery.com/mocahbig/85901-loki-tv-shows-hd-4k-5k-marvel-behance.jpg",
    //     description:"Deep in the Rocky Mountains of Colorado, a government blacksite going by the name Valkyrie, conducts their twisted human experiments trying to push the boundaries of human evolution. Their operation becomes compromised when experiment #030, a.k.a. Sirona, escapes. In a desperate attempt to maintain their secret, Valkyrie hires a group of mercenaries led by Allen Cross to hunt down Sirona and capture her, whatever the cost. Upon finding Sirona, Cross is forced into a no win scenario, do the right thing or follow orders, both of which lead to dire consequences.",
    //     duration:"52 min",
    //     ratings:"8.2",
    //     quality:"HD",
    //     genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
    //     realised:"2021-06-09",
    //     casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
    //     production:"Marvel Studios",
    //     country:"United States of America",
    // },
    // {
    //     id:"14",
    //     title:"Entergalactic",
    //     image:"https://img.sflix.to/xxrz/250x400/224/99/7f/997fdcdc8228bddd182c663a7e16f590/997fdcdc8228bddd182c663a7e16f590.jpg",
    //     wallpaper:"https://images6.alphacoders.com/132/1321794.jpeg",
    //     description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    //     duration:"108 minn",
    //     ratings:"6.2",
    //     quality:"HD",
    //     genre:"Thriller, Drama",
    //     realised:"2023-09-28",
    //     casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
    //     production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
    //     country:"United States of America",
    // },
    // {
    //     id:"15",
    //     title:"Sago Mini Friends",
    //     image:"https://img.sflix.to/xxrz/250x400/224/04/71/04716ddc953df3bdb7178bb63e38c5ae/04716ddc953df3bdb7178bb63e38c5ae.jpg",
    //     wallpaper:"https://www.apple.com/tv-pr/articles/2022/08/apple-tv-reveals-trailer-for-sago-mini-friends-an-adorable-new-preschool-animated-series-based-on-the-award-winning-app-sago-mini-world/images/big-image/big-image-01/083022_Reveals_Trailer_Sago_Mini_Friends_Big_Image_01_big_image_post.jpg.og.jpg",
    //     description:"After stealing the Tesseract during the events of Avengers: Endgame. an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant”or help fix the timeline and stop a greater threat",
    //     duration:"52 min",
    //     ratings:"8.2",
    //     quality:"HD",
    //     genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
    //     realised:"2021-06-09",
    //     casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
    //     production:"Marvel Studios",
    //     country:"United States of America",
    // },
    // {
    //     id:"16",
    //     title:"The Creator",
    //     image:"https://img.sflix.to/xxrz/250x400/224/0b/e7/0be7bc9996857aae6580e0aaf103084a/0be7bc9996857aae6580e0aaf103084a.jpg",
    //     wallpaper:"https://wallpapercg.com/download/john-david-washington-7680x4788-16946.jpg",
    //     description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    //     duration:"108 minn",
    //     ratings:"6.2",
    //     quality:"HD",
    //     genre:"Thriller, Drama",
    //     realised:"2023-09-28",
    //     casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
    //     production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
    //     country:"United States of America",
    // },
    // {
    //     id:"17",
    //     title:"Entergalactic",
    //     image:"https://img.sflix.to/xxrz/250x400/224/99/7f/997fdcdc8228bddd182c663a7e16f590/997fdcdc8228bddd182c663a7e16f590.jpg",
    //     wallpaper:"https://images6.alphacoders.com/132/1321794.jpeg",
    //     description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    //     duration:"108 minn",
    //     ratings:"6.2",
    //     quality:"HD",
    //     genre:"Thriller, Drama",
    //     realised:"2023-09-28",
    //     casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
    //     production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
    //     country:"United States of America",
    // },
    // {
    //     id:"18",
    //     title:"Sago Mini Friends",
    //     image:"https://img.sflix.to/xxrz/250x400/224/04/71/04716ddc953df3bdb7178bb63e38c5ae/04716ddc953df3bdb7178bb63e38c5ae.jpg",
    //     wallpaper:"https://www.apple.com/tv-pr/articles/2022/08/apple-tv-reveals-trailer-for-sago-mini-friends-an-adorable-new-preschool-animated-series-based-on-the-award-winning-app-sago-mini-world/images/big-image/big-image-01/083022_Reveals_Trailer_Sago_Mini_Friends_Big_Image_01_big_image_post.jpg.og.jpg",
    //     description:"After stealing the Tesseract during the events of Avengers: Endgame. an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant”or help fix the timeline and stop a greater threat",
    //     duration:"52 min",
    //     ratings:"8.2",
    //     quality:"HD",
    //     genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
    //     realised:"2021-06-09",
    //     casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
    //     production:"Marvel Studios",
    //     country:"United States of America",
    // },
    // {
    //     id:"19",
    //     title:"The Creator",
    //     image:"https://img.sflix.to/xxrz/250x400/224/0b/e7/0be7bc9996857aae6580e0aaf103084a/0be7bc9996857aae6580e0aaf103084a.jpg",
    //     wallpaper:"https://wallpapercg.com/download/john-david-washington-7680x4788-16946.jpg",
    //     description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    //     duration:"108 minn",
    //     ratings:"6.2",
    //     quality:"HD",
    //     genre:"Thriller, Drama",
    //     realised:"2023-09-28",
    //     casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
    //     production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
    //     country:"United States of America",
    // },
    // {
    //     id:"20",
    //     title:"Loki",
    //     image:"https://lumiere-a.akamaihd.net/v1/images/tra8660_105_trl_comp_v004_7f1c1cb3.jpeg?region=491,0,2858,1608",
    //     wallpaper:"https://rare-gallery.com/mocahbig/85901-loki-tv-shows-hd-4k-5k-marvel-behance.jpg",
    //     description:"After stealing the Tesseract during the events of Avengers: Endgame. an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant”or help fix the timeline and stop a greater threat",
    //     duration:"52 min",
    //     ratings:"8.2",
    //     quality:"HD",
    //     genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
    //     realised:"2021-06-09",
    //     casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
    //     production:"Marvel Studios",
    //     country:"United States of America",
    // },
    // {
    //     id:"21",
    //     title:"The Marsh King's Daughter",
    //     image:"https://img.sflix.to/xxrz/250x400/224/f4/55/f4554ab27d86f77087c693db75b661fd/f4554ab27d86f77087c693db75b661fd.jpg",
    //     wallpaper:"https://m.media-amazon.com/images/S/sonata-images-prod/US_TVOD_TheMarshKingsDaughter_PVOD_SH/d6f6de4a-541f-4c0e-8570-9faf668420ca._UR1920,1080_SX1440_FMjpg_.jpeg",
    //     description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    //     duration:"108 minn",
    //     ratings:"6.2",
    //     quality:"HD",
    //     genre:"Thriller, Drama",
    //     realised:"2023-09-28",
    //     casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
    //     production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
    //     country:"United States of America",
    // },
    // {
    //     id:"22",
    //     title:"Wish",
    //     image:"https://images.justwatch.com/poster/309134585/s592/wish-2023",
    //     wallpaper:"https://images.hdqwalls.com/wallpapers/disney-wish-2023-kv.jpg",
    //     description:"Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
    //     duration:"52 min",
    //     ratings:"8.2",
    //     quality:"HD",
    //     genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
    //     realised:"2021-06-09",
    //     casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
    //     production:"Marvel Studios",
    //     country:"United States of America",
    // },
    // {
    //     id:"23",
    //     title:"Mission: Impossible - Dead Reckoning Part One",
    //     image:"https://img.sflix.to/xxrz/250x400/224/e5/a0/e5a02d6b78afd13554c6737c1da83cae/e5a02d6b78afd13554c6737c1da83cae.jpg",
    //     wallpaper:"https://images.hdqwalls.com/wallpapers/2023-mission-impossible-dead-reckoning-part-one-poster-8e.jpg",
    //     description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    //     duration:"108 minn",
    //     ratings:"6.2",
    //     quality:"HD",
    //     genre:"Thriller, Drama",
    //     realised:"2023-09-28",
    //     casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
    //     production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
    //     country:"United States of America",
    // },
    // {
    //     id:"24",
    //     title:"Sirona",
    //     image:"https://img.sflix.to/xxrz/250x400/224/03/64/03641b0e4d09722be48de99a4c7236d9/03641b0e4d09722be48de99a4c7236d9.jpg",
    //     wallpaper:"https://rare-gallery.com/mocahbig/85901-loki-tv-shows-hd-4k-5k-marvel-behance.jpg",
    //     description:"Deep in the Rocky Mountains of Colorado, a government blacksite going by the name Valkyrie, conducts their twisted human experiments trying to push the boundaries of human evolution. Their operation becomes compromised when experiment #030, a.k.a. Sirona, escapes. In a desperate attempt to maintain their secret, Valkyrie hires a group of mercenaries led by Allen Cross to hunt down Sirona and capture her, whatever the cost. Upon finding Sirona, Cross is forced into a no win scenario, do the right thing or follow orders, both of which lead to dire consequences.",
    //     duration:"52 min",
    //     ratings:"8.2",
    //     quality:"HD",
    //     genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
    //     realised:"2021-06-09",
    //     casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
    //     production:"Marvel Studios",
    //     country:"United States of America",
    // },
    // {
    //     id:"25",
    //     title:"Entergalactic",
    //     image:"https://img.sflix.to/xxrz/250x400/224/99/7f/997fdcdc8228bddd182c663a7e16f590/997fdcdc8228bddd182c663a7e16f590.jpg",
    //     wallpaper:"https://images6.alphacoders.com/132/1321794.jpeg",
    //     description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    //     duration:"108 minn",
    //     ratings:"6.2",
    //     quality:"HD",
    //     genre:"Thriller, Drama",
    //     realised:"2023-09-28",
    //     casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
    //     production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
    //     country:"United States of America",
    // },
    // {
    //     id:"26",
    //     title:"Sago Mini Friends",
    //     image:"https://img.sflix.to/xxrz/250x400/224/04/71/04716ddc953df3bdb7178bb63e38c5ae/04716ddc953df3bdb7178bb63e38c5ae.jpg",
    //     wallpaper:"https://www.apple.com/tv-pr/articles/2022/08/apple-tv-reveals-trailer-for-sago-mini-friends-an-adorable-new-preschool-animated-series-based-on-the-award-winning-app-sago-mini-world/images/big-image/big-image-01/083022_Reveals_Trailer_Sago_Mini_Friends_Big_Image_01_big_image_post.jpg.og.jpg",
    //     description:"After stealing the Tesseract during the events of Avengers: Endgame. an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant”or help fix the timeline and stop a greater threat",
    //     duration:"52 min",
    //     ratings:"8.2",
    //     quality:"HD",
    //     genre:"Sci-Fi & Fantasy, Action & Adventure, Drama, Crime",
    //     realised:"2021-06-09",
    //     casts:" Tom Hiddleston, Owen Wilson, Wunmi Mosaku, Gugu Mbatha-Raw, Tara Strong",
    //     production:"Marvel Studios",
    //     country:"United States of America",
    // },
    // {
    //     id:"27",
    //     title:"The Creator",
    //     image:"https://img.sflix.to/xxrz/250x400/224/0b/e7/0be7bc9996857aae6580e0aaf103084a/0be7bc9996857aae6580e0aaf103084a.jpg",
    //     wallpaper:"https://wallpapercg.com/download/john-david-washington-7680x4788-16946.jpg",
    //     description:"Helena, a woman living a seemingly ordinary life, hides a dark secret: her father is the infamous “Marsh King,” the man who kept her and her mother captive in the wilderness for years. After a lifetime of trying to escape her past, Helena is forced to face her demons when her father unexpectedly escapes from prison.",
    //     duration:"108 minn",
    //     ratings:"6.2",
    //     quality:"HD",
    //     genre:"Thriller, Drama",
    //     realised:"2023-09-28",
    //     casts:" Daisy Ridley, Ben Mendelsohn, Garrett Hedlund, Caren Pistorius, Dan Abramovici",
    //     production:"Black Bear Pictures, Anonymous Content, STX Films, STX Entertainment",
    //     country:"United States of America",
    // },
]

export default MoviesArray